version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped

  theia:
    build:
      context: ./frontend
      dockerfile: Dockerfile.theia
    ports:
      - "3001:3000"
    volumes:
      - ./:/workspace:cached
    restart: unless-stopped
